### ISSUE TITLE
iTerm2 issue

### ISSUE THREAD

**Issue by fedgrant** [jpadilla/redisapp#10]
Hey this doesn't work with iTerm2. The issue looks to be with the conditional [here](https://github.com/fedgrant/redisapp/blob/master/Redis/AppDelegate.swift#L81)

`
if appExists("iTerm") {            
} else {
}
`

I think the else block AppleScript instructions don't work with iTerm2.

**Comment by hsiunien** [comment]
It is true, I hope it can be fixed

**Comment by jpadilla** [comment]
Recently released a new version. this should be fixed.
