### ISSUE TITLE
how can i run this app with my redis.conf

### ISSUE THREAD

**Issue by mengdodo** [jpadilla/redisapp#15]
my environment is docker, i want use php/nginx in docker and redis by this app.
the phpRedisAdmin throw this error:
Fatal error: Uncaught Predis\Response\ServerException: DENIED Redis is running in protected mode because protected mode is enabled,……

how can i run this app with my redis.conf

thx!

**Comment by FerdinaKusumah** [comment]
I think you should see in this path  ```/Applications/Redis.app/Contents/Resources/Vendor/redis```

**Comment by mengdodo** [comment]
thx

**Comment by alexventuraio** [comment]
I could not update the config file because it was ReadOnly, any other suggestion?
https://github.com/jpadilla/redisapp/issues/5#issuecomment-1450748514
