### ISSUE TITLE
OS X 10.10 support?

### ISSUE THREAD

**Issue by iwaszko** [jpadilla/redisapp#6]
I'd love to use Redis.app on Mac OS X 10.10 (Yosemite). What would be required to support it?

**Comment by jpadilla** [comment]
@iwaszko mind giving the latest release a try?

**Comment by iwaszko** [comment]
Not at all! Thanks so much for a quick response. Unfortunately, it doesn't work for me and in fact now it seems to require OS X 10.12:

<img width="590" alt="screen shot 2017-02-10 at 20 49 26" src="https://cloud.githubusercontent.com/assets/1711875/22841702/db16f5fe-efd2-11e6-82ed-eda0ac040184.png">

Now, I know nothing about OS X development but in your latest commit you've changed MACOSX_DEPLOYMENT_TARGET value from 10.11 to 10.12: https://github.com/jpadilla/redisapp/commit/a3a790f8c0ce6b0441fdc14def0bd2bbe84850f3#diff-180e11bed2814d8de9bd17532e0dbbb4R223. How about putting 10.10 there? ;)

**Comment by jpadilla** [comment]
@iwaszko my bad, just got another build out. Let me know

**Comment by iwaszko** [comment]
It works! Wow, that was really quick. Thanks a lot!
